# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
users = User.create([{ full_name: 'John Doe' }, { full_name: 'Jane Doe' }, { full_name: 'Jon Smith' }])
book1 = Book.create({ title: 'Inferno', author: 'The Great Gatsby'})
book2 = Book.create({ title: 'Inferno', author: 'F Scott Fitzgerald', })
book1.reviews.create({ content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', user: users[0]})
book2.reviews.create(    
    { content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus accumsan tempor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed lacus tellus. Nulla a dapibus tortor, sit amet blandit odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin placerat justo in leo gravida, vel molestie eros convallis. In porttitor, sem ut tempor semper, dui mi placerat neque, eget pretium purus est molestie neque.

# Sed ultrices ex eu augue sagittis imperdiet. Etiam sed ante at lorem porttitor blandit. Quisque eu tempus libero, ac pretium lectus. Curabitur at lectus metus. Phasellus cursus mollis nulla, in condimentum lectus iaculis vitae. Duis luctus nec orci et ullamcorper. Vivamus porttitor tincidunt dui sit amet facilisis. Nulla ac tristique lectus. Proin sodales sit amet sem sit amet commodo. Sed luctus, eros ac facilisis condimentum, felis ligula tristique purus, egestas posuere tellus ex sed sapien.

# Nulla auctor, lacus sed condimentum varius, quam nisl ultrices lorem, a tincidunt nisi dolor et mauris. Curabitur sollicitudin massa id justo malesuada, placerat porttitor sapien tempor. Praesent malesuada vel orci quis lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse potenti. Vivamus porttitor est tellus, at tincidunt justo commodo eget. In aliquam eros felis. Nam metus ex, porta et pharetra non, scelerisque et leo. Vestibulum sed purus tortor. Mauris lacinia ex sed risus bibendum, at tempus nulla vulputate. Sed dapibus libero vel luctus accumsan. Integer interdum tempor erat, sit amet auctor odio luctus at. Suspendisse vehicula felis vitae bibendum lobortis. Sed viverra blandit faucibus. Integer eget turpis massa. Nam metus metus, pharetra in nulla quis, pulvinar interdum tellus.

# Sed vitae hendrerit odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer non nibh rutrum, faucibus ante ut, consectetur turpis. Suspendisse a nulla ornare, fermentum metus tempor, tempor odio. Nunc semper at augue a porta. Vestibulum ut eleifend nunc. Quisque arcu eros, lacinia vel nibh eu, scelerisque luctus diam.

# Phasellus quis odio sagittis, gravida erat nec, hendrerit ex. Aliquam erat volutpat. Proin dictum viverra nunc, vel egestas neque. Proin fringilla risus vulputate enim sagittis, id aliquet ligula porttitor. Donec sagittis justo eget lacus consectetur semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque convallis imperdiet tincidunt. Aenean quis fermentum augue, vel vestibulum ante. Cras pretium aliquet magna, sed malesuada felis ultricies in.', user: users[0]})
book2.reviews.create(    
    { content: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?', user: users[1]},
)
